### PR TITLE
Mapping algorithm change

### PR DESCRIPTION
**Pull request by lauken13**
I changed the underlying code structure that creates the mappings between different levels. I moved to extracting a matrix of connections and using an algorithm inspired by complete linkage clustering algorithms. I think it's more robust to different specifications. 

I also changed the resulting naming to default to the survey data naming convention. We could change this to the population, or to allow the user to choose. Previously we took the level with the smallest combination of other levels for readability i.e, 

if sample was c(18-25, 25-55, 56+)
and popn was c(18-55, 56+)

we would have used 18-55, 56+ previously but now use 18-25 + 25-55, 56+. Although a little messier I think this is clearer to the user what is going on. Because we often know less about the population, defaulting to the population would generally result in shorter factor names.

### CODE REVIEW

**Comment by lauken13** [comment]
Merge #104 and #102 before merging this

**Comment by lauken13** [comment]
Retry with drop = FALSE to hopefully clean up the code

**Comment by lauken13** [comment]
Added doc and changed to using drop = FALSE - thanks for the comments @jgabry! 

I've stuffed up brms on my machine again, so I can't confirm the tests run, but all that I can check seem to!

**Comment by jgabry** [comment]
> I've stuffed up brms on my machine again, so I can't confirm the tests run, but all that I can check seem to!

No worries, I just ran the tests and the relevant tests for this PR all seem to be passing. The only tests failing for me are the ones comparing the estimates to a value +- tolerance, but they only sometimes fail. That's a separate issue related to #107 (which I just opened), so I think for this PR all the needed tests are OK.

**Comment by jgabry** [comment]
Actually one of the visual tests for the plot method was failing because this PR affects the x-axis labels for the plot by age level. I will regenerate the reference image(s) to get them passing again.

**Comment by lauken13** [comment]
Hey @jgabry does this have anything for me to do before merging?

**Pull request merged**
