### PR TITLE
Remove troublesome code

### PR DESCRIPTION
**Pull request by lauken13**
Removed the code we discussed in this weeks meeting and confirmed the tests run. Closes Issue #117

### CODE REVIEW

**Comment by lauken13** [comment]
Requesting @Dewi-Amaliah  because I think this is a good first code review

**Review by jgabry — APPROVED** [review]
Thanks! Will merge now

**Comment by jgabry** [comment]
> Requesting @Dewi-Amaliah because I think this is a good first code review

Oh crap, sorry! I didn't see this comment before merging it.

**Comment by lauken13** [comment]
All good! Happy it's merged! @Dewi Amaliah ***@***.***> We'll
find another one for you to review. :)

**Pull request merged**
